# Generated by Django 4.2 on 2023-06-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default='C:\\Users\\asus\\Desktop\\Deskbottom\\ImCloud\\icloud\\media\\image', max_length=64),
        ),
    ]
