# Generated by Django 4.2 on 2023-06-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_archive_alter_image_options_alter_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='icon_color',
            new_name='color',
        ),
    ]
