# Generated by Django 4.2 on 2023-06-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_rename_icon_color_archive_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='color',
        ),
    ]
