# Generated by Django 4.2 on 2023-06-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0011_remove_archive_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='images',
            field=models.ManyToManyField(to='cloud.image', verbose_name='Изображения'),
        ),
    ]
